# Generated by Django 4.2.2 on 2023-06-26 08:10

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  
                ('password', models.TextField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.CharField(max_length=50, default='False', verbose_name='superuser status')),
                ('is_staff', models.CharField(max_length=50, default='False', verbose_name='staff status')),
                ('is_active', models.IntegerField(default=1, verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')), 
                ('email', models.CharField(max_length=254, verbose_name='Email Address')),
                ('name', models.TextField(max_length=100)),
                ('bio', models.CharField(max_length=1000, blank=True)),
                ('image', models.CharField(max_length=100, blank=True)),
                ('followers', models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)),
                ('groups', models.CharField(max_length=50)),
                ('user_permissions', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': True,
            },
        ),
    ]
